name: CI 

on: [ push, pull_request ] 

jobs: 
  build: 
    runs-on: ubuntu-latest 

  steps: 
    - uses: actions/checkout@v4
    with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
    repository: 'my-first-github-actions'
            
    - name: Run a one-line script 
      run: echo Hello, world! 
